const SAVE_CLIENT = '[CLIENT_FORM] SAVE_CLIENT';
const SAVE_ALL_CLIENTS = '[CLIENT_FORM] SAVE_ALL_CLIENTS';

export {
    SAVE_CLIENT,
    SAVE_ALL_CLIENTS
}
/* const clientTypes = {
    SAVE_CLIENT: '[CLIENT_FORM] SAVE_CLIENT',
    SAVE_ALL_CLIENTS: '[CLIENT_FORM] SAVE_ALL_CLIENTS'
  };
  
  export {
  clientTypes
  } */